#yaml.conf
redis:
  default:
    host: 127.0.0.1
    port: 6379
  testing:
    host: 127.0.0.1
    port: 6379
  staging:
      host: 127.0.0.1
      port: 6379
  production:
      host: 127.0.0.1
      port: 6379
